#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/include/utils.tci:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/include/utils.tci
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/xdc.tci
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/template.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/om2.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/IPackage.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/package.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/bld.js
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/bld/package.xs
package.mak: config.bld
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/package.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/io/File.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/io/File.xs
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/io/package.xs:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/services/io/package.xs
package.mak: package.bld
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/tools/configuro/template/compiler.opt.xdt
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: F:/Program\ Files/Texas\ Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.arm.elf.M3.rootDir ?= F:/PROGRA~1/TEXASI~1/ccsv5.2.1/ccsv5/tools/compiler/tms470_4.9.5
ti.targets.arm.elf.packageBase ?= F:/Program Files/Texas Instruments/ccsv5.2.1/xdctools_3_23_03_53/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,em3 .dlls: app.pem3

-include package/cfg/app_pem3.mak
-include package/cfg/app_pem3.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_pem3.dep
endif
app.pem3: package/cfg/app_pem3.xdl
	@


ifeq (,$(wildcard .libraries,em3))
app.pem3 package/cfg/app_pem3.c: .libraries,em3
endif

package/cfg/app_pem3.c package/cfg/app_pem3.h package/cfg/app_pem3.xdl: override _PROG_NAME := app.xem3
package/cfg/app_pem3.c: package/cfg/app_pem3.cfg

clean:: clean,em3
	-$(RM) package/cfg/app_pem3.cfg
	-$(RM) package/cfg/app_pem3.dep
	-$(RM) package/cfg/app_pem3.c
	-$(RM) package/cfg/app_pem3.xdc.inc

clean,em3::
	-$(RM) app.pem3
.executables,em3 .executables: app.xem3

app.xem3: |app.pem3

-include package/cfg/app.xem3.mak
app.xem3: package/cfg/app_pem3.oem3 
	$(RM) $@
	@$(MSG) lnkem3 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.M3.rootDir)/bin/lnk470 -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@).  -q -o $@ package/cfg/app_pem3.oem3   package/cfg/app_pem3.xdl --silicon_version=7M3 --strict_compatibility=on -c -m $(XDCCFGDIR)/$@.map  -l $(ti.targets.arm.elf.M3.rootDir)/lib/rtsv7M3_T_le_eabi.lib
	
app.xem3: export C_DIR=
app.xem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/;$(PATH)
app.xem3: Path:=$(ti.targets.arm.elf.M3.rootDir)/bin/;$(PATH)

app.test test,em3 test: app.xem3.test

app.xem3.test:: app.xem3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 app.xem3.test
else
	@$(MSG) running $<  ...
	$(call EXEC.app.xem3, ) 
endif

clean,em3::
	-$(RM) .tmp,app.xem3,0,*


clean:: clean,em3

clean,em3::
	-$(RM) app.xem3
clean:: 
	-$(RM) package/cfg/app_pem3.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
app_pem3.oem3,copy : package/cfg/app_pem3.oem3
app_pem3.sem3,copy : package/cfg/app_pem3.sem3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
configPkg.tar: package/package.bld.xml
configPkg.tar: package/package.ext.xml
configPkg.tar: package/package.rel.dot
configPkg.tar: package/build.cfg
configPkg.tar: package/package.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml:

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
clean:: 
	-$(RM) package/configPkg.pjt
